feat(templates): make prepare script more robust

diff --git a/src/create_python_starter/templates/common/scripts/prepare b/src/create_python_starter/templates/common/scripts/prepare
--- a/src/create_python_starter/templates/common/scripts/prepare
+++ b/src/create_python_starter/templates/common/scripts/prepare
@@ -1,19 +1,15 @@
 # !/usr/bin/env sh
 
-d="$(dirname "$dir")/.github/hooks"
+hooks_dir=".github/hooks"
 
-git config --local core.hooksPath "$d"
+cd "$(dirname "$0")/../"
+
+git config --local core.hooksPath "$hooks_dir"
 
 RED='\033[0;31m'
 
-prepare_hook() {
-  if ! [[ -x "$1" ]] && command -v chmod &> /dev/null; then
-    chmod +x "$1"
-    echo "$1"
-  else
-    printf "${RED} Could not set github hooks file located at $1 as executable. Make sure to do so before proceeding\n"
-  fi
-}
+if ! command -v chmod &>/dev/null; then
+  printf "${RED}Could not set github hooks files located in "$hooks_dir" as executable. Make sure to do so before proceeding\n"
+fi
 
-prepare_hook "$d/pre-commit"
-prepare_hook "$d/commit-msg"
+find ".github/hooks" -type f -exec chmod +x {} \;
